package io.temco.guhada.common.enum

enum class ImageUploadTarget(val type: String) {
    IMAGE("IMAGE"),
    IMAGE_BRAND("IMAGE_BRAND"),
    IMAGE_BRAND_THUMBNAIL("IMAGE_BRAND_THUMBNAIL"),
    IMAGE_BRAND_DETAIL("IMAGE_BRAND_DETAIL"),
    IMAGE_PRODUCT("IMAGE_PRODUCT"),
    IMAGE_PRODUCT_THUMBNAIL("IMAGE_PRODUCT_THUMBNAIL"),
    IMAGE_PRODUCT_DETAIL("IMAGE_PRODUCT_DETAIL"),
    DOC_PRODUCT_CERTIFICATE("DOC_PRODUCT_CERTIFICATE"),
    IMAGE_PRODUCT_OPTION("IMAGE_PRODUCT_OPTION"),
    IMAGE_PRODUCT_OPTION_THUMBNAIL("IMAGE_PRODUCT_OPTION_THUMBNAIL"),
    IMAGE_PRODUCT_OPTION_DETAIL("IMAGE_PRODUCT_OPTION_DETAIL"),
    IMAGE_USER("IMAGE_USER"),
    IMAGE_USER_SELLER("IMAGE_USER_SELLER"),
    DOC_USER_SELLER("DOC_USER_SELLER"),
    IMAGE_PRODUCT_REVIEW("IMAGE_PRODUCT_REVIEW"),
    IMAGE_BBS("IMAGE_BBS"),
    IMAGE_BBS_COMMENT("IMAGE_BBS_COMMENT"),
    DOCUMENT("DOCUMENT")
}
