package io.temco.guhada.common.enum

enum class PointStatus(val status: String) {
    DUE_SAVE("DUE_SAVE"),
    SAVED("SAVED"),

    DUE_CONSUMPTION("DUE_CONSUMPTION"),
    CONSUMPTION("CONSUMPTION"),

    DUE_SAVE_CANCEL("DUE_SAVE_CANCEL"),
    SAVED_CANCEL("SAVED_CANCEL"),
    DUE_CONSUMPTION_CANCEL("DUE_CONSUMPTION_CANCEL"),
    CONSUMPTION_CANCEL("CONSUMPTION_CANCEL"),
    RESTORE_CANCEL("RESTORE_CANCEL"),
    EXPIRED_CANCEL("EXPIRED_CANCEL"),

    RESTORE("RESTORE"),
    EXPIRED("EXPIRED")
}