package io.temco.guhada.common.enum

enum class PurchaseStatus(val status: String) {
    WAITING_PAYMENT("WAITING_PAYMENT"),
    COMPLETE_PAYMENT("COMPLETE_PAYMENT"),
    SELLER_IDENTIFIED("SELLER_IDENTIFIED"), // 상품 준비중 상태로 취급
    RELEASE_PRODUCT("RELEASE_PRODUCT"),     // 상품 준비중 상태로 취급
    DELIVERING("DELIVERING"),
    DELIVERED("DELIVERED"),
    REQUEST_CANCEL("REQUEST_CANCEL"),
    COMPLETE_CANCEL("COMPLETE_CANCEL"),
    SALE_CANCEL("SALE_CANCEL"),
    REQUEST_EXCHANGE("REQUEST_EXCHANGE"),
    PICKING_EXCHANGE("PICKING_EXCHANGE"),
    COMPLETE_PICK_EXCHANGE("COMPLETE_PICK_EXCHANGE"),
    RESEND_EXCHANGE("RESEND_EXCHANGE"),
    COMPLETE_EXCHANGE("COMPLETE_EXCHANGE"),
    WITHDRAW_EXCHANGE("WITHDRAW_EXCHANGE"),
    REQUEST_RETURN("REQUEST_RETURN"),
    PICKING_RETURN("PICKING_RETURN"),
    COMPLETE_PICK_RETURN("COMPLETE_PICK_RETURN"),
    COMPLETE_RETURN("COMPLETE_RETURN"),
    WITHDRAW_RETURN("WITHDRAW_RETURN")
}